language: java
# Blocklist
branches:
    except:
      - gh-pages 
before_script:
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
  - curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN 
    on:
      branch: master 
    local_dir: target/surefire-reports 
  
